#!/usr/bin/env bash

set -e

PHP_VERSION=7.4

function msg {
    echo "========================================"
    echo "$1"
    echo "========================================"
}

msg "Making site-manager globally accessible"
echo "sudo ln -s $(pwd)/site-manager /usr/local/bin/site-manager"
sudo ln -s $(pwd)/site-manager /usr/local/bin/site-manager

# Add ppa
msg "Adding ppa for nginx and php"
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:nginx/stable -y
LC_ALL=C.UTF-8 sudo add-apt-repository ppa:ondrej/php -y
sudo apt-get update

# Install nginx and php
msg "Installing nginx"
sudo apt-get install -y nginx

msg "Installing php"
sudo apt-get install -y php${PHP_VERSION}-fpm php${PHP_VERSION}-cli php${PHP_VERSION}-mysql php${PHP_VERSION}-pgsql php${PHP_VERSION}-curl php${PHP_VERSION}-redis php${PHP_VERSION}-mbstring php${PHP_VERSION}-gd php${PHP_VERSION}-xml php${PHP_VERSION}-zip php${PHP_VERSION}-intl php${PHP_VERSION}-readline php${PHP_VERSION}-json php${PHP_VERSION}-opcache

# Setup nginx
msg "Setting up nginx"
sudo rm /etc/nginx/sites-enabled/default
sudo rm /etc/nginx/sites-available/default
echo 'fastcgi_param HTTP_PROXY "";' | sudo tee -a /etc/nginx/fastcgi.conf 1> /dev/null
echo 'fastcgi_param HTTP_PROXY "";' | sudo tee -a /etc/nginx/fastcgi_params 1> /dev/null
echo 'proxy_set_header Proxy "";' | sudo tee -a /etc/nginx/proxy_params 1> /dev/null

# Setup php
msg "Setting up php"
sudo sed -i "s/log_errors = .*/log_errors = On/" /etc/php/${PHP_VERSION}/cli/php.ini
sudo sed -i "s/error_reporting = .*/error_reporting = E_ALL/" /etc/php/${PHP_VERSION}/cli/php.ini
sudo sed -i "s/display_errors = .*/display_errors = Off/" /etc/php/${PHP_VERSION}/cli/php.ini
sudo sed -i "s/memory_limit = .*/memory_limit = 512M/" /etc/php/${PHP_VERSION}/cli/php.ini
sudo sed -i "s/;date.timezone.*/date.timezone = UTC/" /etc/php/${PHP_VERSION}/cli/php.ini
sudo sed -i "s/upload_max_filesize = .*/upload_max_filesize = 100M/" /etc/php/${PHP_VERSION}/fpm/php.ini
sudo sed -i "s/post_max_size = .*/post_max_size = 100M/" /etc/php/${PHP_VERSION}/fpm/php.ini
sudo sed -i "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/" /etc/php/${PHP_VERSION}/fpm/php.ini
sudo mkdir /var/log/sites
sudo chown www-data:www-data /var/log/sites

# Install composer
msg "Installing composer"
curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer

# Restart services
msg "Restarting nginx and php-fpm"
sudo service nginx restart
sudo service php${PHP_VERSION}-fpm restart
