#!/usr/bin/env bash

set -e

function msg {
    echo "========================================"
    echo "$1"
    echo "========================================"
}

# Add ppa
msg "Adding ppa for nginx and php"
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:nginx/stable -y
LC_ALL=C.UTF-8 sudo add-apt-repository ppa:ondrej/php -y
sudo apt-get update

# Install nginx and php
msg "Installing nginx"
sudo apt-get install -y nginx

msg "Installing php"
sudo apt-get install -y php7.2-fpm php7.2-cli \
php7.2-mysql php7.2-pgsql php7.2-sqlite3 \
php7.2-curl php7.2-memcached php7.2-redis \
php7.2-imap php7.2-mbstring php7.2-gd \
php7.2-xml php7.2-zip php7.2-soap \
php7.2-intl php7.2-readline php7.2-json php7.2-opcache

# Setup nginx
msg "Setting up nginx"
sudo rm /etc/nginx/sites-enabled/default
sudo rm /etc/nginx/sites-available/default
echo 'fastcgi_param HTTP_PROXY "";' | sudo tee -a /etc/nginx/fastcgi.conf 1> /dev/null
echo 'fastcgi_param HTTP_PROXY "";' | sudo tee -a /etc/nginx/fastcgi_params 1> /dev/null
echo 'proxy_set_header Proxy "";' | sudo tee -a /etc/nginx/proxy_params 1> /dev/null

# Setup php
msg "Setting up php"
sudo sed -i "s/error_reporting = .*/error_reporting = E_ALL/" /etc/php/7.2/cli/php.ini
sudo sed -i "s/display_errors = .*/display_errors = Off/" /etc/php/7.2/cli/php.ini
sudo sed -i "s/memory_limit = .*/memory_limit = 512M/" /etc/php/7.2/cli/php.ini
sudo sed -i "s/;date.timezone.*/date.timezone = UTC/" /etc/php/7.2/cli/php.ini
sudo sed -i "s/upload_max_filesize = .*/upload_max_filesize = 100M/" /etc/php/7.2/fpm/php.ini
sudo sed -i "s/post_max_size = .*/post_max_size = 100M/" /etc/php/7.2/fpm/php.ini
sudo sed -i "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/" /etc/php/7.2/fpm/php.ini

# Install composer
msg "Installing composer"
curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer

# Restart services
msg "Restarting nginx and php-fpm"
sudo service nginx restart
sudo service php7.2-fpm restart
